server:
  port: 8005

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ilerijava
    username: devuser
    password: devpassword
    driver-class-name: org.postgresql.Driver

springdoc:
  api-docs:
    path: /api-docs

microservices:
  user: http://localhost:8007
  order: http://localhost:8003
  gateway: http://localhost:8001
  payment: http://localhost:8006
  product: http://localhost:8002
  invoice: http://localhost:8008
  notification: http://localhost:8004
  shipment: http://localhost:8011
